# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build Release

on:
  push:
    tags:
      - x*
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Cmake
        uses: jwlawson/actions-setup-cmake@v1.13
      - name: Compile Modules (Linux and Mac)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: cd build_tools && make build
      - name: Compile Modules (Windows)
        if: matrix.os == 'windows-latest'
        run: cd build_tools && .\build.bat build
      - name: Compile LectureCut
        run: cargo build --release
      - name: Collect Artifacts (Linux and Mac)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          mkdir -p lecturecut${{ matrix.os }} &&
          cp target/release/lecturecut lecturecut${{ matrix.os }} &&
          cp -r modules lecturecut${{ matrix.os }}
      - name: Collect Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir lecturecut${{ matrix.os }} &&
          cp target\release\lecturecut.exe lecturecut${{ matrix.os }} &&
          cp -r modules lecturecut${{ matrix.os }}
      - name: Compress Artifacts (Linux and Mac)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: tar -czf lecturecut${{ matrix.os }}.tar.gz lecturecut${{ matrix.os }}
      - name: Compress Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: 7z a lecturecut${{ matrix.os }}.zip lecturecut${{ matrix.os }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lecturecut${{ matrix.os }}
          path: |
              lecturecut${{ matrix.os }}.tar.gz
              lecturecut${{ matrix.os }}.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./lecturecutubuntu-latest/lecturecutubuntu-latest.tar.gz
            ./lecturecutwindows-latest/lecturecutwindows-latest.zip
            ./lecturecutmacos-latest/lecturecutmacos-latest.tar.gz
          draft: false
          prerelease: false